kind: pipeline
name: check-builds

steps:
  - name: check-vuejs-builds
    image: node:lts
    commands:
      - make npm-init
      - ./check-vuejs-builds.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
